spring:
  application:
    name: spring-admin-server
  main:
    banner-mode: off
  profiles:
    active:
      - secure

server:
  port: 8787

---

spring:
  profiles: insecure

info.tags.security: insecure

