spring:
  application:
    name: spring-admin-client
  main:
    banner-mode: off
  profiles:
    active:
      - secure
  boot:
    admin:
      client:
        url: http://localhost:8787
server:
  port: 8788